/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  ayran
 * Created: Mar 20, 2018
 */

INSERT INTO professions (name, profession_id) VALUES 
('ADMINISTRADOR', 1),
('ADMINISTRADOR DE EDIFICIO', 2),
('ADMINISTRADOR DE EXPLORACAO AGRICOLA', 3),
('ADMINISTRADORES', 4),
('ADVOGADO', 5),
('ADVOGADO DIREITO DO TRABALHO', 6),
('AGENCIADOR DE PROPAGANDA', 7),
('AGENTE ADMINISTRATIVO', 8),
('AGENTE DE COMPRAS', 9),
('AGENTE DE VENDA DE SERVICOS AS EMPRESAS', 10),
('AGENTE DE VIAGEM', 11),
('AGENTE PUBLICITARIO', 12),
('AGENTE TECNICO DE VENDAS', 13),
('AGENTES ADMINISTRATIVOS', 14),
('AGENTES DE ADMINISTRACAO DE EMPRESAS PUBLICAS E PRIVADAS', 15),
('ALMOXARIFE', 16),
('ANALISTA DE CARGOS E SALARIOS', 17),
('ANALISTA DE COMERCIALIZACAO', 18),
('ANALISTA DE COMUNICACA 8234    ANALISTA DE CREDITO E COBRANCA', 19);