/**
 * Author:  ayran
 * Created: Mar 20, 2018
 */

insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Jodi Kagan', '1995-08-03', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'jkagan0', 452, 24.387, 58, 68, 1, 1, 7, 12);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Annie Treacher', '1992-09-18', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'atreacher1', 835, 50.062, 31, 48, 3, 2, 16, 16);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Earle Tuley', '1990-05-24', 'Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', 'etuley2', 1107, 75.321, 36, 56, 4, 4, 15, 15);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Byran McCullagh', '1999-09-01', 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'bmccullagh3', 1853, 22.972, 48, 58, 3, 2, 2, 14);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Xever Mably', '1979-07-21', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', 'xmably4', 1478, 49.415, 27, 32, 2, 4, 8, 13);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Laurent Swyndley', '1964-08-20', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 'lswyndley5', 1751, 97.352, 43, 50, 4, 2, 4, 12);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Neal Kellog', '1966-04-04', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 'nkellog6', 876, 84.432, 54, 64, 3, 1, 10, 11);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Danette Smaling', '1969-10-04', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'dsmaling7', 326, 42.692, 27, 33, 2, 4, 6, 10);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Jude Delafoy', '1990-10-17', 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 'jdelafoy8', 1623, 18.165, 32, 45, 1, 3, 9, 9);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Alberto Mertin', '1989-02-20', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'amertin9', 1642, 1.918, 20, 22, 1, 4, 6, 8);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Emelita Elster', '1970-08-11', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', 'eelstera', 139, 98.742, 45, 55, 3, 2, 7, 7);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Seymour Penley', '1994-02-17', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'spenleyb', 961, 77.608, 43, 53, 3, 1, 5, 6);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Kristen Kuban', '1983-10-23', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'kkubanc', 1101, 81.598, 26, 44, 4, 3, 2, 5);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Erminia Tipping', '1989-02-23', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae, Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 'etippingd', 2347, 23.439, 50, 60, 1, 1, 3, 4);
insert into people (name, birth_date, about_me, username, elo_score_rating, max_distance_kilometer, age_range_start, age_range_end, sexual_orientation_id, gender_id, profession_id, street_id) values
('Darb Gadman', '1995-05-17', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 'dgadmane', 1095, 91.132, 23, 56, 3, 1, 1, 3);